apiVersion: v2
name: taskflow-chart
description: A Helm chart for deploying the TaskFlow capstone project across dev, stage, and prod environments.
type: application
version: 0.1.0
appVersion: "1.0.0"
