{{- if not .Values.secrets.useKeyVault }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-creds
type: Opaque
stringData:
  username: {{ .Values.database.env.postgresUser | default "postgres" | quote }}
  password: {{ .Values.database.env.postgresPassword | default "password" | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: {{ .Values.database.env.postgresDb | default "taskdb" | quote }}
