{{- if .Values.secrets.useKeyVault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-azure-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"      # We use Workload Identity or Managed Identity
    useVMManagedIdentity: "true" # Simpler for this demo (Node Identity)
    userAssignedIdentityID: ""   # If using specific identity
    keyvaultName: {{ .Values.secrets.keyVaultName }}
    cloudName: ""                # [OPTIONAL] for Gov/China clouds
    objects:  |
      array:
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: postgres-user
          objectType: secret
    tenantId: {{ .Values.secrets.tenantId }}
  secretObjects:
  - secretName: {{ .Release.Name }}-db-creds
    type: Opaque
    data:
    - objectName: postgres-password
      key: password
    - objectName: postgres-user
      key: username
    # Note: 'name' (db name) is not usually secret, so we might need to handle it separately or assume it comes from values still.
    # For now, let's assume postgres-db is mostly static or coming from configmap for prod.
{{- end }}
