name: Deploy to PROD

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_BACKEND: taskflow-backend
  ECR_REPOSITORY_FRONTEND: taskflow-frontend

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push (Release)
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG ./backend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG
        
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG ./frontend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    environment: production # Requires manual approval in GitHub
    steps:
    - uses: actions/checkout@v3
    
    - name: Update Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA_PROD }}" | base64 -d > ~/.kube/config
        
    - name: Deploy to EKS (Prod Namespace)
      env:
        IMAGE_TAG: ${{ github.sha }} 
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY_URL }} 
      run: |
        helm upgrade --install taskflow ./k8s/taskflow-chart \
          --namespace prod --create-namespace \
          -f k8s/taskflow-chart/values-prod.yaml \
          --set image.tag=$IMAGE_TAG \
          --set image.repository=$ECR_REGISTRY/taskflow-backend \
          --wait --atomic --timeout 10m
