name: Deploy to DEV

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'k8s/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_BACKEND: taskflow-backend
  ECR_REPOSITORY_FRONTEND: taskflow-frontend

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Get AWS Account ID for ECR URL
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "ECR_REGISTRY_URL=${ACCOUNT_ID}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com" >> $GITHUB_ENV

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push
      env:
        ECR_REGISTRY: ${{ env.ECR_REGISTRY_URL }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG ./backend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG
        
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG ./frontend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials (Deploy)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set dynamic env vars (Registry URL)
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "ECR_REGISTRY_URL=${ACCOUNT_ID}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com" >> $GITHUB_ENV
    
    - name: Update Kubeconfig
      run: aws eks update-kubeconfig --name taskflow-dev-cluster --region ${{ env.AWS_REGION }}
        
    - name: Deploy to EKS (Dev Namespace)
      env:
        IMAGE_TAG: ${{ github.sha }}
        ECR_REGISTRY: ${{ env.ECR_REGISTRY_URL }} 
      run: |
        helm upgrade --install taskflow ./k8s/taskflow-chart \
          --namespace dev --create-namespace \
          --set image.tag=$IMAGE_TAG \
          --set image.repository=$ECR_REGISTRY/taskflow-backend \
          --wait --atomic
